### ISSUE TITLE
ts 报红如何解决

### ISSUE THREAD

**Issue by DeepDarkFantasy233** [YeMao-Zi/pinia-plugin-piniastorage#1]
通过uni cli 创建的项目， 官网推荐的版本是pinia@2.0.33 ，在注册main.ts时，

`store.use(piniaStorage());` 

piniaStorage()这部分ts 会报红提示如下

`类型“import("F:/code/vue3Cli/my-vue3-project/node_modules/pinia-plugin-piniastorage/node_modules/pinia/dist/pinia").PiniaPlugin”的参数不能赋给类型“import("F:/code/vue3Cli/my-vue3-project/node_modules/pinia/dist/pinia").PiniaPlugin”的参数。
  参数“context”和“context” 的类型不兼容。
    不能将类型“import("F:/code/vue3Cli/my-vue3-project/node_modules/pinia/dist/pinia").PiniaPluginContext<string, import("F:/code/vue3Cli/my-vue3-project/node_modules/pinia/dist/pinia").StateTree, import("F:/code/vue3Cli/my-vue3-project/node_modules/pinia/dist/pinia")._GettersTree<import("F:/code/vue3Cli/my-vue3-project/node_modul...”分配给类型“import("F:/code/vue3Cli/my-vue3-project/node_modules/pinia-plugin-piniastorage/node_modules/pinia/dist/pinia").PiniaPluginContext<string, import("F:/code/vue3Cli/my-vue3-project/node_modules/pinia-plugin-piniastorage/node_modules/pinia/dist/pinia").StateTree, import("F:/code/vue3Cli/my-vue3-project/node_modules/pini...”。
      在这些类型中，"options.getters" 的类型不兼容。
        不能将类型“(import("F:/code/vue3Cli/my-vue3-project/node_modules/pinia/dist/pinia")._GettersTree<import("F:/code/vue3Cli/my-vue3-project/node_modules/pinia/dist/pinia").StateTree> & ThisType<...>) | undefined”分配给类型“(import("F:/code/vue3Cli/my-vue3-project/node_modules/pinia-plugin-piniastorage/node_modules/pinia/dist/pinia")._GettersTree<import("F:/code/vue3Cli/my-vue3-project/node_modules/pinia-plugin-piniastorage/node_modules/pinia/dist/pinia").StateTree> & ThisType<...>) | undefined”。
          不能将类型“_GettersTree<StateTree> & ThisType<StateTree & _StoreWithGetters<_GettersTree<StateTree>> & PiniaCustomProperties<...>>”分配给类型“(_GettersTree<StateTree> & ThisType<StateTree & _StoreWithGetters<_GettersTree<StateTree>> & PiniaCustomProperties<...>>) | undefined”。`

但是升级pinia 到2.1.6版本时，run dev:h5无法启动项目, 显示白屏 报错

`Uncaught SyntaxError: The requested module '/node_modules/vue-demi/lib/index.mjs?v=7d0ccb56' does not provide an export named 'hasInjectionContext' (at pinia.mjs:6:10)`

**Comment by YeMao-Zi** [comment]
你可以先这样试试:
1.使用vite创建一个标准vue项目，然后
npm引入Uniapp
2.插件下载到本地运行看看
等我有空看看cli是什么情况，之前我的Uniapp和正常vue项目都是没问题的

**Comment by DeepDarkFantasy233** [comment]
可能是我直接cli  Uniapp的问题？官网上 `npx degit dcloudio/uni-preset-vue#vite-ts my-vue3-project`
反复尝试了一下虽然报红，但是实际功能不受影响，持久化是好用的

 然后main.ts 报红的部分直接断言掉了 但是感觉应该有更好的处理方法
`pinia.use(piniaStorage() as any);`

store.ts 的文件使用 // @ts-ignore 强行禁用了

`
 // @ts-ignore  
        storeOptions: {
            openStorage: true, // 必须为 true 才会运行插件
            storageWay: {
                setStorageWay: (key: any, data: string) => localStorage.setItem(key, data), sessionStorage
                getStorageWay: (key: string) => localStorage.getItem(key),
            },
            paths: ['fontSizeType', 'isThemDark'] // 只持久化 token
        },`

**Comment by YeMao-Zi** [comment]
奇怪，我用cli是没有报错的

![pinia](https://s2.loli.net/2023/08/18/Q7MjXNTYSa2O9xl.png)

还有你说的那个升级pinia 到2.1.6版本时，run dev:h5无法启动项目, 显示白屏 报错是因为cli创建的vue版本低于3.3不兼容pinia 2.0.36以上的版本

**Comment by YeMao-Zi** [comment]
tsconfig.json 里加入这个看看 "strictFunctionTypes": false,

**Comment by YeMao-Zi** [comment]
找到问题了，现在解决了，我发包的时候指定了pinia依赖导致有两个pinia依赖，两个版本pinia类型冲突了，不清楚为什么cli的项目会校验这个
